<!DOCTYPE html>
<script>
    $(function(){
            $('#add-position-form').dialog({
                autoOpen: false,
                modal:    true,
                buttons:  {
                    'Save' : function(){
                        $.post('/position/add-position', $("#position-form").serialize())
                            .done(function(data){
                                $("#main").html(data);
                                $("#add-position-form").dialog("close");
                            });
//                        $(this).dialog("close");
                    },
                    'Cancel' : function(){
                        $(this).dialog("close");
                    }
                }
            });
             
            $("#add-position-btn").button()
                                  .click(function(){
                                        $("#add-position-form").dialog("open");
                                  });
    });
</script>

<div id="add-position-form" title="Add new position">
    <form id="position-form">
        <label for="positionName">Position Name</label>
        <input type="text" id="positionName" name="positionName" />
        <label for="positionCode">Position Code</label>
        <input type="text" id="positionCode" name="positionCode" />
        <input type="hidden" id="objectId" name="objectId" value="2">
        <input type="hidden" id="domainId" name="domainId" value="1">
    </form>
</div>

<button id="add-position-btn">Add position</button>

<div id="main"></div>