<script>
    $(document).ajaxError(function(event, jqxhr, settings, exception){
        $("#result-message").html(jqxhr.status);
    });

    $(document).ajaxSuccess(function(event, jqxhr, settings){
        $("#result-message").html(jqxhr.status);
    });

    $(function(){
        $("#update-node-btn").button().click(function(){
            $.post('<?php echo $this->url(array('controller' => 'objects', 'action' => 'edit-object'), null, true); ?>',
            $("#node-form").serialize()); 
               
        })
    });
    
</script>

<?php echo $this->form; ?>