<?php

switch ($this->objectType) {
    case 'level': echo $this->partial('partials/object-lists/level-list.phtml', array('levels'=>$this->objects));
        break;
    case 'element': echo $this->partial('partials/object-lists/element-list.phtml', array('elements'=>$this->objects));
        break;
    case 'position': echo $this->partial('partials/object-lists/position-list.phtml', array('positions'=>$this->objects));
        break;
    case 'user': echo $this->partial('partials/object-lists/user-list.phtml', array('users'=>$this->objects));
        break;
    case 'orgobject': echo $this->partial('partials/object-lists/orgobject-list.phtml', array('orgobjects'=>$this->objects));
        break;
    default : echo $this->partial('partials/object-lists/level-list.phtml', array('levels'=>$this->objects));
}
