<!DOCTYPE html>
<script>
    function deleteObject(objType, objId) {
        $.post("<?php echo $this->url(array('controller' => 'objects', 'action' => 'delete'), null, true); ?>",
                {'objectType': objType, 'id': objId},
        function(data) {
            // Our controller returns JSON
            if (1 == data.error) {
                $("#result-message").append('<div data-alert class="alert-box"><a href="#" class="close">&times</a>' + data.message + '</div>');
            } else {
                // If no error just reload the page to reflect changes
                location.reload();
            }
        }
        );

    }
</script>
<div id="result-message">
</div>
<div class="object-list">
    <?php
    // We don't need to display Add button in case of privilege edition
    if ('privilege' !== $this->objectName) {
        ?>
        <button class="btn btn-primary" onClick="javascript:window.location.replace('<?php echo $this->url(array('controller' => 'objects', 'action' => 'add-object', 'objectType' => $this->objectName)); ?>')"><?php echo $this->translate('add new ' . $this->objectName); ?></button>
        <?php
    }
    //    echo $this->partial('partials/object-forms/' . $this->objectName . '-form.phtml', array('subobjects' => $this->subobjects));
    echo $this->partial('partials/object-lists/' . $this->objectName . '-list.phtml', array($this->objectName . 's' => $this->objects, 'subobjects' => $this->subobjects));
    ?>
</div>
<div class="object-help">
</div>