<script>
    function deleteEntry(item){
        $(item).remove();
        $("#counter").val(Number($("#counter").val())-1);
        
    }
    
    function addUser(){
        var counter = $("#counter").val();
        $("#counter").val(Number(counter)+1);
        $("#usersLoc").before('<tr id='+
                $("#counter").val()+
                '><td><a href="#" onClick="deleteEntry(\'#'+
                $("#counter").val()+
                '\')">&times</a></td><td>'+
                $("#userId option:selected").text()+
                '<input type="hidden" id="orderPos_'+
                $("#userId").val()+
                '" name="orderPos_'+
                $("#userId").val()+
                '" value="'+
                $("#counter").val()+
                '"></td></tr>');
    }
    
    function addScenario() {
        if (Number($("#counter").val()) == 0) {
            $("#addUserButton").tooltip({title: 'You should add users to scenario.', placement: 'right'});
            $("#addUserButton").tooltip('show');
        } else {
            $("#new-scenario").submit();
        }
    }
    
 </script>
<div class='col-lg-6'>
<?php
echo $this->form;

?>
</div>