<script>

    function deleteItem(itemId) {
        item = '#item_' + itemId;
        $(item).remove();
        inputItem = '#itemName_' + itemId;
        $(inputItem).remove();
        inputValue = '#value_' + itemId;
        $(inputValue).remove();
        element = '#elementId_' + itemId;
        $(element).remove();
    }
     
    function AddItem(){
        var counter = $("#counter").val();
        counter++;
        $("#counter").val(counter);
        $("#itemsLoc").before('<tr id="item_' + counter + '"><td id="item-name">' + $("#itemName").val() + '</td><td>'+$('#expType option:selected').text()+'</td><td id="item-value">' + Number($("#value").val()).toFixed(2) + '</td><td id="item-delete-icon"><a href="#" onClick=deleteItem(' + counter + ')>&times</a></td></tr>');
        $("#counter").after('<input type="hidden" id="itemName_' + counter + '" name="itemName_' + counter + '" value="' + $("#itemName").val() + '">');
        $("#counter").after('<input type="hidden" id="value_' + counter + '" name="value_' + counter + '" value="' + $("#value").val() + '">');
        $("#counter").after('<input type="hidden" id="elementId_' + counter + '" name="elementId_' + counter + '" value="' + $("#expType").val() + '">');
    
    }
    
    function setExpTypes() {
        $("#expType").load("<?php echo $this->url(array('controller'=>'form', 'action'=>'set-exp-types')); ?>", {expGroup: $("#expgroup").val()});
    }
    
    $(function(){
        if ( -1 !== $("#expgroup").val()) {
            setExpTypes();
        }
    });
        
</script>

<?php
echo $this->form;
?>