<script>
    function addForm(){
        window.location = "<?php echo $this->url(array('controller' => 'form', 'action' => 'edit-form'), null, true); ?>";
    }
    
    function openForm(formId){
        $('#form-open').load('<?php echo $this->url(array('controller' => 'form', 'action' => 'open-form'), null, true); ?>' + '/formId/' + formId.slice(formId.indexOf('_')+1));
        //location = url;
    }
</script>
<!-- GLOBAL CONTAINER FOR FORMS LIST AND FORM DETAILS -->
<div>

    <!--  Forms list goes here -->
    <div class="large-8 columns">
        <?php
        if (is_array($this->forms)) {
            echo '<table>';
            foreach ($this->forms as $form) {
                $class = '';
                if ($form['form']->final) {
                    if ('approve' == $form['form']->decision) {
                        $class = ' class="approved" ';
                    } else {
                        $class = ' class="declined" ';
                    }
                }
                if (!$form['form']->public) {
                    $class.=' private ';
                }
                echo '<tr ' . $class . ' onClick="openForm(\'form_' . $form['form']->formId . '\')" >' . PHP_EOL .
                '<td>' . PHP_EOL .
                (!empty($form['parentNode']) ? $form['parentNode']->nodeName : '') . PHP_EOL .
                '</td><td>' . $form['node']->nodeName . '</td>' . PHP_EOL .
                '<td>' . PHP_EOL .
                substr($form['form']->date, 0, strpos($form['form']->date, ' ')) . '</td>' . PHP_EOL .
                '<td>' . $form['owner']->userName . '</td>' . PHP_EOL .
                '<td>' . $form['contragent']->contragentName . '</td>' . PHP_EOL .
                '<td>' . $form['form']->formName . '</td>' . PHP_EOL .
                '<td>' . sprintf("%01.2f", $form['total']) . '</td>' . PHP_EOL .
                '</tr>';
            }
            echo '</table>';
        }
        ?>

        <!-- Paginator -->
        <div class="pagination-centered">
            <ul class="pagination">
                <li class="arrow <?php echo ($this->currentPage == 1) ? 'unavailable': ''; ?>"><a href="<?php echo $this->url(array('controller'=>'form', 'action'=>'index', 'page'=>1), null, true);?>">&laquo;</a></li>
                <?php
                if ($this->pages > 1) {
                    for ($i = 1; $i <= $this->pages; $i++) {
                        if ($i == $this->currentPage) {
                            $class = 'class="current"';
                        } else {
                            $class = '';
                        }
                        echo "<li $class ><a href='" . $this->url(array('controller'=>'form', 'action'=>'index', 'page'=>$i), null, true) . "'>" . $i . '</a></li>' . PHP_EOL;
                    }
                }
                ?>
                <li class="arrow <?php echo ($this->currentPage == $this->pages) ? 'unavailable': ''; ?>"><a href="<?php echo $this->url(array('controller'=>'form', 'action'=>'index', 'page'=>$this->pages), null, true); ?>">&raquo;</a></li>
            </ul>
        </div>
        <!-- End of PAGINATOR -->


    </div>
    <!-- END Forms list -->


    <!-- Form's details -->
    <div id="form-open" class="large-4 columns"></div>
    <!-- END Forms details -->
    <button id="add-form-btn" onclick="addForm()"><?php echo $this->translate('add form'); ?></button>

</div>
<!-- END GLOBAL CONTAINER -->