<form id="domain" method="post" action="<?php echo $this->url(array('controller'=>'index', 'action'=>'new-domain'), null, true);?>">
    <table> 
        <tr>
            <td>
                <label for="domainName">Domain name</label></td>
            <td>
                <input type="text" id="domainName" name="domainName" /></td>
        </tr>
    </table>
    <button id="signup" value="signup">Add domain</button>
</form>
