<div id="add-object-form" title="Add new position">
    <form id="object-form">
        <select id="expgroup" name="expgroup">
            <option disabled><?php echo $this->translate('expgroup');?></option>
            <?php 
                foreach ($this->subobjects['expgroup']->toArray() as $group){
                    echo '<option value="' . $group . '">' . $group . '</option>';
                }
            ?>
        </select>
        <input type="text" id="elementName" name="_elementName" placeholder="<?php echo $this->translate('element'); ?>"/>
        <input type="text" id="elementCode" name="_elementCode" placeholder="<?php echo $this->translate('element code'); ?>"/></td>
        <input type="text" id="elementComment" name="_elementComment" placeholder="<?php echo $this->translate('element comment'); ?>"/></td>
        <input type="hidden" id="objectType" name="objectType" value="element"></td>
    </form>
</div>

<button id="add-object-btn">Add element</button>
