<div id="add-object-form" title="<?php echo $this->translate('add new node'); ?>">
    <form id="object-form">
        <div>
            <label for="nodeName"><?php echo $this->translate('node name'); ?></label>
        </div>
        <div>
            <input type="text" name="_nodeName" placeholder="<?php echo $this->translate('node name'); ?>" />
        </div>
        <div>
            <label for="parentNodeId"><?php echo $this->translate('parent node');?></label>
        </div>
        <?php
        if (!empty($this->subobjects['nodes']) && is_array($this->subobjects['nodes'])) {
            echo '<select  id="parentNodeId" name="_parentNodeId">';
            echo '<option value="-1">' . $this->translate('no parent') . '</option>';
            foreach ($this->subobjects['nodes'] as $node) {
                echo '<option " value="' .
                $node->nodeId . '">' .
                $node->nodeName .
                '</option>';
            }
            echo '</select>';
        } else {
            echo '<input type="hidden" id="parentNodeId" name="_parentNodeId" value="-1">';
        }
        ?>
        <input type="hidden" id="objectType" name="objectType" value="node">

    </form>
</div>

<button id="add-object-btn"><?php echo $this->translate('add new node');?></button>
