<div id="add-object-form" title="<?php echo $this->translate('add new position');?>">
    <form id="object-form">
        <div>
            <label for="positionName"><?php echo $this->translate('position name'); ?></label>
        </div>
        <div>
            <input type="text" id="positionName" name="_positionName" placeholder="<?php echo $this->translate('position name'); ?>"/>
        </div>

        <?php
        if (isset($this->subobjects['nodes'])) {
            echo "<label for='nodeId'>" . $this->translate('select node') . "</label>" . PHP_EOL;
            echo '<select id="nodeId" name="nodeId">' . PHP_EOL;
            foreach ($this->subobjects['nodes'] as $node) {
                echo "<option value='$node->nodeId'>$node->nodeName</option>" . PHP_EOL;
            }
            echo "</select>" . PHP_EOL;
        }
        ?>
        <input type="hidden" id="domainId" name="_domainId" value="1">
        <input type="hidden" id="objectType" name="objectType" value="position">

    </form>
</div>

<button id="add-object-btn"><?php echo $this->translate('add new position');?></button>
