<div id="add-object-form" title="<?php echo $this->translate('add new template');?>">
    <form id="object-form">
        <label for="type"><?php echo $this->translate('template type'); ?></label>
        <select id="type" name="type">
            <option disabled><?php echo $this->translate('template type');?></option>
            <?php 
            if (isset($this->subobjects['types'])) {
                foreach ($this->subobjects['types'] as $type){
                    echo '<option value="' . $type . '">' . $this->translate($type) . '</option>';
                }
            }
            ?>
        </select>
        <label for="language"><?php echo $this->translate('language'); ?></label>
        <select id="language" name="language">
            <option disabled><?php echo $this->translate('language');?></option>
            <?php 
            if (isset($this->subobjects['locales'])) {
                foreach ($this->subobjects['locales'] as $lang){
                    echo '<option value="' . $lang . '">' . $this->translate($lang) . '</option>';
                }
            }
            ?>
        </select>
        <label for="templateName"><?php echo $this->translate('template name'); ?></label>
        <input type="text" id="templateName" name="_templateName" placeholder="<?php echo $this->translate('template name'); ?>"/>
        <label for="body"><?php echo $this->translate('template body'); ?></label>
        <textarea id="body" name="_body"><?php echo $this->translate('template body'); ?></textarea></td>
        <input type="hidden" id="objectType" name="objectType" value="template"></td>
    </form>
</div>

<button id="add-object-btn"><?php echo $this->translate('add new template');?></button>
