<div id="add-object-form" title="Add new user">
    <form id="object-form">
        <label for="userName">User Name</label>
        <input type="text" id="userName" name="userName" />
        <label for="login">User login</label>
        <input type="text" id="login" name="login" />
        <label for="positionId">Position Id</label>
        <input type="text" id="positionId" name="positionId" />
        <input type="hidden" id="password" name="password" value="ttt">
        <input type="hidden" id="domainId" name="domainId" value="1">
    </form>
</div>

<button id="add-object-btn">Add user</button>

<div id="main">
    <?php echo $this->partial('partials/object-lists/user-list.phtml');?>
</div>