<div id="add-object-form" title="<?php echo $this->translate('add new user'); ?>">
    <form id="object-form">
        <div>
            <label for="userName"><?php echo $this->translate('name'); ?></label>
        </div>
        <div>
            <input type="text" id="userName" name="_userName" placeholder="<?php echo $this->translate('name');?>"/>
        </div>
        <div>
            <label for="login"><?php echo $this->translate('email'); ?></label>
        </div>
        <div>
            <input type="text" id="login" name="_login" placeholder="<?php echo $this->translate('email');?>"/>
        </div>
        <div>

            <label for="positionId"><?php echo $this->translate('position'); ?></label>
        </div>
        <?php
        if (is_array($this->subobjects['positions']) && !empty($this->subobjects['positions'])) {
            echo '<select id="positionId" name="_positionId">' . PHP_EOL;
            foreach ($this->subobjects['positions'] as $position) {
                echo '<option value="' . $position->positionId . '">' . $position->positionName . '</option>' . PHP_EOL;
            }
            echo '</select>' . PHP_EOL;
        }
        ?>
        <div>
            <label for="password"><?php echo $this->translate('password'); ?></label>
        </div>
        <div>
            <input type="password" id="password" name="_password" placeholder="<?php echo $this->translate('password');?>">
        </div>
        <input type="hidden" id="objectType" name="objectType" value="user">
    </form>
</div>

<button id="add-object-btn"><?php echo $this->translate('add new user'); ?></button>

<div id="main">
    <?php echo $this->partial('partials/object-lists/user-list.phtml'); ?>
</div>