<div >
    <table width="100%">
        <?php
        if (is_array($this->nodes)) {
            foreach ($this->nodes as $node) {
                echo '<tr>' . PHP_EOL .
                            '<td><a href="#" onclick="deleteObject(\'node\', '. $node->nodeId .')">&times</a>' . PHP_EOL .
                            '</td>' . PHP_EOL .
                            '<td><a href="' . $this->url(array('controller' => 'objects',
                                        'action' => 'open-object',
                                        'objectType' => 'node',
                                        'nodeId' => $node->nodeId)) .
                                    '">' . $node->nodeName . '</a>' . PHP_EOL .
                                    '</td>' . PHP_EOL .
                            '<td>' . $node->parentNodeId .
                            '</td>'. PHP_EOL .
                    '</tr>';
            }
        }
        ?>
    </table>
</div>
