<div class="panel">
    <?php
    if (is_array($this->nodes)) {
        foreach ($this->nodes as $node) {
            echo '<div class="row"><div class="small-1 columns"><a href="' . $this->url(array('controller' => 'objects',
                'action' => 'delete',
                'objectType' => 'node',
                'nodeId' => $node->nodeId), null, true) .
            '">x</a></div><div class="small-1 columns"><a href="' . $this->url(array('controller' => 'objects',
                'action' => 'open-object',
                'objectType' => 'node',
                'nodeId' => $node->nodeId)) .
            '">' . $node->nodeName .
            '</a></div><div class="small-1 columns">' . $node->parentNodeId .
            '</div></div>';
        }
    }
    ?>
</div>
