<table>
<?php
if (is_array($this->users)){
    foreach ($this->users as $user) {
        echo '<tr>' . PHP_EOL;
        echo '<td><a href="'.
                $this->url(array('controller'=>'objects',
                                 'action'=>'delete',
                                 'userId'=>$user->userId,
                                 'objectType'=>'user')).
                '">x</a></td>' . PHP_EOL;
        echo '<td>' . $user->userName . '</td>' . PHP_EOL;
        echo '<td>' . $user->login . '</td>' . PHP_EOL;
        echo '<td>' . $user->positionId . '</td>' . PHP_EOL;
        echo '<td><a href="' . $this->url(array('controller' => 'objects',
                                                'action' => 'user-privileges',
                                                'userId' => $user->userId)) .
             '">Privileges </td>' . PHP_EOL;
        echo '</tr>' . PHP_EOL;
    }
}
?>
</table>
